version: '3.1'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4t5
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: caiohenrks
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_dir:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: q1w2e3r4t5
    ports:
      - "8090:80"
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  mysql_dir:

